#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.
#
name: xpanse-ui

# Run this workflow every time a new commit push to the repository
on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install all required NPM packages
              working-directory: ./
              run: npm install
            - name: Run EsLint
              working-directory: ./
              run: npx eslint . --ext .js,.jsx,.ts,.tsx --config package.json --max-warnings=0
            - name: Run knip
              working-directory: ./
              run: npx knip
            - name: Run unit tests
              working-directory: ./
              run: npm run test
